### ISSUE TITLE
Permit2: Example for PermitBatchTransferFrom

### ISSUE THREAD

**Issue by clement-ux** [dragonfly-xyz/useful-solidity-patterns#10]
Hello 👋

I've followed your patterns for `PermitTransferFrom` utilization and I've tried to apply it to the `PermitBatchTransferFrom` version.
But because the signature for the user, for "batched version" is different from the "original" version, I've modified the helpers functions : `_signPermitt()` and especially `_getEIP712Hash` in order to fit to the new version. Attached the modification I've done.
![Capture d’écran 2023-01-03 à 17 08 35](https://user-images.githubusercontent.com/55331875/210395601-82cba4d8-e58d-42c8-bf5f-2e3562c9a4d9.png)

But I receive this error with I'm testing it : "InvalidSigner()". So I assume that the hash that I'm generating is wrong. 
I've you can provide a quick example on how generate the hash for batched permit2 transfer, this could be really useful! 

Thanks a lot in advance 😁

**Comment by clement-ux** [comment]
Update : I've solved the issue by doing something like this. 
![Capture d’écran 2023-01-04 à 10 55 28](https://user-images.githubusercontent.com/55331875/210529937-e153c984-ba56-4fc3-9651-fe96a02c905c.png)

Note : I've merged the _getEIP712Hash and _signPermit function.

**Comment by merklejerk** [comment]
Nice, beat me to it! Yup, arrays of structs need to be hashed individually then their concatenation is hashed again. :dizzy:
