### ISSUE TITLE
Add an example for `PermitBatchTransferFrom`

### ISSUE THREAD

**Issue by trojanMcAfee** [dragonfly-xyz/useful-solidity-patterns#19]
This has been an extremely useful example (as the name says it) for knowing how Permit2 works. 

I believe it'd go full circe if you guys could add a working example for how it would be with `PermitBatchTransferFrom`.

**Comment by sebastiantf** [comment]
Would like to reopen this and have this added

**Comment by merklejerk** [comment]
addressed in 1a51d77377d50a25a947448395ca215e8f6813c2
